### PR TITLE
Update build-wheels.yml

### PR DESCRIPTION
**Pull request by mbestipa**
This PR is a first attempt at automating the upload of the tmtools bdists to pypi. 

Taken from https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

### CODE REVIEW

**Comment by jvkersch** [comment]
My bad, I didn't realize this was a PR off my other PR, and GitHub closed it automatically when I merged my PR.

**Comment by jvkersch** [comment]
@mbestipa Thanks for doing this! I've uploaded a token for the PyPI **test** repository and I've merged your PR into my branch. I'll test this against the testing PyPI instance and then merge into main when everything is OK.

I would like the full wheel building workflow to be triggered when a new GitHub release is created, and I would also like to automatically upload the source distribution. If that is something that you want to get your hands dirty on, feel free to take a shot at it!

**Comment by jvkersch** [comment]
@mbestipa I've added your commit to #17, which also handles uploading the source distribution, and triggering the build when a new release is made.  Thanks for your contribution -- the new wheels are now on PyPI.

**Comment by mbestipa** [comment]
@jvkersch, sorry I couldn't get to it before now! Glad to see you managed to get it to work :)

**Pull request merged**
